spring:
  profiles:
    active: dev
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: 47.97.193.126
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6001/eureka/
  server:
    enable-self-preservation: false
---
server:
  port: 6001
spring:
  profiles: prod
  application:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: 47.97.193.126
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6001/eureka/
  server:
    enable-self-preservation: true
